name: Cleanup Branches (Reusable)

on:
  workflow_call:
    inputs:
      dryRun:
        description: 'Run in dry-run mode'
        required: false
        type: boolean
        default: true

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      # Checkout the calling repository if needed (optional)
      - name: Checkout calling repository
        uses: actions/checkout@v3

      # Checkout the shared workflows repository where the cleanup script is stored
      - name: Checkout shared repository
        uses: actions/checkout@v3
        with:
          repository: ETrigosNivelics/shared-workflows
          path: shared

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install PyGithub

      - name: Execute cleanup script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ inputs.dryRun }}" == "true" ]; then
            python shared/.github/scripts/cleanup_branches.py --dry-run
          else
            python shared/.github/scripts/cleanup_branches.py
          fi
